
spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    host: 120.79.23.207
    port: 5673
    username: liuye
    password: liuye
    virtualHost: /
    listener:
      simple:
          retry:
              #最大重试次数
              max-attempts: 5
              #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
              enabled: true
              #重试间隔时间（单位毫秒
              initial-interval: 4000
          #重试次数超过上面的设置之后是否丢弃（false不丢弃时需要代码实现将该消息加入死信队列）
          default-requeue-rejected: false
          #简单队列开启ack 手动确定
          acknowledge-mode: manual
    publisher-confirms: true